// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: add_column_data.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addColumnData = `-- name: AddColumnData :one
INSERT INTO column_data (id, idx, value, column_id, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    ?,
    ?,
    (SELECT id FROM columns WHERE name = ? AND sheet_id = ?),
    datetime('now'),
    datetime('now')
)
RETURNING id, idx, value, column_id, created_at, updated_at
`

type AddColumnDataParams struct {
	Idx     int64
	Value   sql.NullString
	Name    string
	SheetID uuid.UUID
}

func (q *Queries) AddColumnData(ctx context.Context, arg AddColumnDataParams) (ColumnDatum, error) {
	row := q.db.QueryRowContext(ctx, addColumnData,
		arg.Idx,
		arg.Value,
		arg.Name,
		arg.SheetID,
	)
	var i ColumnDatum
	err := row.Scan(
		&i.ID,
		&i.Idx,
		&i.Value,
		&i.ColumnID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
