// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: add_column.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addColumn = `-- name: AddColumn :one
INSERT INTO columns (id, name, type, required, sheet_id, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    ?,
    ?,
    ?,
    ?,
    datetime('now'),
    datetime('now')
)
RETURNING id, name, type, required, sheet_id, created_at, updated_at
`

type AddColumnParams struct {
	Name     string
	Type     string
	Required bool
	SheetID  uuid.UUID
}

func (q *Queries) AddColumn(ctx context.Context, arg AddColumnParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, addColumn,
		arg.Name,
		arg.Type,
		arg.Required,
		arg.SheetID,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Required,
		&i.SheetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
