// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bulk_add_column_data.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const bulkAddColumnData = `-- name: BulkAddColumnData :exec
INSERT INTO column_data (id, idx, value, type, column_id, created_at, updated_at)
VALUES 
    (gen_random_uuid(), ?, ?, ?, ?, datetime('now'), datetime('now'))
`

type BulkAddColumnDataParams struct {
	Idx      int64
	Value    sql.NullString
	Type     sql.NullString
	ColumnID uuid.UUID
}

func (q *Queries) BulkAddColumnData(ctx context.Context, arg BulkAddColumnDataParams) error {
	_, err := q.db.ExecContext(ctx, bulkAddColumnData,
		arg.Idx,
		arg.Value,
		arg.Type,
		arg.ColumnID,
	)
	return err
}
