// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: change_game_url.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const changeGameUrl = `-- name: ChangeGameUrl :exec
UPDATE tables 
SET game_url = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type ChangeGameUrlParams struct {
	GameUrl sql.NullString
	ID      uuid.UUID
}

func (q *Queries) ChangeGameUrl(ctx context.Context, arg ChangeGameUrlParams) error {
	_, err := q.db.ExecContext(ctx, changeGameUrl, arg.GameUrl, arg.ID)
	return err
}
