// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create_column.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createColumn = `-- name: CreateColumn :one
INSERT INTO columns (id, name, type, required, sheet_id, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    ?,
    ?,
    ?,
    ?,
    datetime('now'),
    datetime('now')
)
RETURNING id, name, type, required, sheet_id, created_at, updated_at, source_column_id
`

type CreateColumnParams struct {
	Name     string
	Type     string
	Required bool
	SheetID  uuid.UUID
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, createColumn,
		arg.Name,
		arg.Type,
		arg.Required,
		arg.SheetID,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Required,
		&i.SheetID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceColumnID,
	)
	return i, err
}
