// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create_table.sql

package database

import (
	"context"
	"database/sql"
)

const createTable = `-- name: CreateTable :one
INSERT INTO tables (id, game_url, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    ?,
    datetime('now'),
    datetime('now')
)
RETURNING id, game_url, created_at, updated_at, name
`

func (q *Queries) CreateTable(ctx context.Context, gameUrl sql.NullString) (Table, error) {
	row := q.db.QueryRowContext(ctx, createTable, gameUrl)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.GameUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
