// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create_sheet.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSheet = `-- name: CreateSheet :one
INSERT INTO sheets (id, name, type, branch_id, created_at, updated_at, source_sheet_id)
VALUES (
    gen_random_uuid(),
    ?,
    ?,
    ?,
    datetime('now'),
    datetime('now'),
    ?
)
RETURNING id, name, branch_id, created_at, updated_at, type, source_sheet_id
`

type CreateSheetParams struct {
	Name          string
	Type          string
	BranchID      uuid.UUID
	SourceSheetID sql.NullString
}

func (q *Queries) CreateSheet(ctx context.Context, arg CreateSheetParams) (Sheet, error) {
	row := q.db.QueryRowContext(ctx, createSheet,
		arg.Name,
		arg.Type,
		arg.BranchID,
		arg.SourceSheetID,
	)
	var i Sheet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.SourceSheetID,
	)
	return i, err
}
