// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create_sheet.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createSheet = `-- name: CreateSheet :one
INSERT INTO sheets (id, name, type, branch_id, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    ?,
    ?,
    ?,
    datetime('now'),
    datetime('now')
)
RETURNING id, name, branch_id, created_at, updated_at, type
`

type CreateSheetParams struct {
	Name     string
	Type     string
	BranchID uuid.UUID
}

func (q *Queries) CreateSheet(ctx context.Context, arg CreateSheetParams) (Sheet, error) {
	row := q.db.QueryRowContext(ctx, createSheet, arg.Name, arg.Type, arg.BranchID)
	var i Sheet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}
