// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_column.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteColumn = `-- name: DeleteColumn :exec
DELETE FROM columns
WHERE name = ? AND sheet_id = ?
`

type DeleteColumnParams struct {
	Name    string
	SheetID uuid.UUID
}

func (q *Queries) DeleteColumn(ctx context.Context, arg DeleteColumnParams) error {
	_, err := q.db.ExecContext(ctx, deleteColumn, arg.Name, arg.SheetID)
	return err
}
