// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_branch.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteBranch = `-- name: DeleteBranch :exec
DELETE FROM branches 
WHERE id = ?
`

func (q *Queries) DeleteBranch(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBranch, id)
	return err
}
