// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_row.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteRow = `-- name: DeleteRow :exec
DELETE FROM column_data 
WHERE column_id IN (
    SELECT c.id 
    FROM columns c 
    WHERE c.sheet_id = ?1
) 
AND idx = ?2
`

type DeleteRowParams struct {
	SheetID uuid.UUID
	Idx     int64
}

func (q *Queries) DeleteRow(ctx context.Context, arg DeleteRowParams) error {
	_, err := q.db.ExecContext(ctx, deleteRow, arg.SheetID, arg.Idx)
	return err
}
