// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_multiple_column_data.sql

package database

import (
	"context"
)

const deleteMultipleColumnData = `-- name: DeleteMultipleColumnData :exec
DELETE FROM column_data
WHERE id IN (/*SLICE:ids*/)
`

func (q *Queries) DeleteMultipleColumnData(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteMultipleColumnData)
	return err
}
