// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_table.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteTable = `-- name: DeleteTable :exec
DELETE FROM tables 
WHERE id = ?
`

func (q *Queries) DeleteTable(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTable, id)
	return err
}
