// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_sheet.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteSheet = `-- name: DeleteSheet :exec
DELETE FROM sheets 
WHERE id = ?
`

func (q *Queries) DeleteSheet(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSheet, id)
	return err
}
