// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_columns_data.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getColumnsData = `-- name: GetColumnsData :many
select id, idx, value, column_id, created_at, updated_at from column_data cd
where column_id = ?
`

func (q *Queries) GetColumnsData(ctx context.Context, columnID uuid.UUID) ([]ColumnDatum, error) {
	rows, err := q.db.QueryContext(ctx, getColumnsData, columnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ColumnDatum
	for rows.Next() {
		var i ColumnDatum
		if err := rows.Scan(
			&i.ID,
			&i.Idx,
			&i.Value,
			&i.ColumnID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
