// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_sheet.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getSheet = `-- name: GetSheet :one
select id, name, branch_id, created_at, updated_at from sheets
where id = ?
`

func (q *Queries) GetSheet(ctx context.Context, id uuid.UUID) (Sheet, error) {
	row := q.db.QueryRowContext(ctx, getSheet, id)
	var i Sheet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
