// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_table_from_sheet.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getTableFromSheet = `-- name: GetTableFromSheet :one
select t.id, t.game_url, t.created_at, t.updated_at, t.name from sheets s
join branches b on s.branch_id = b.id
join tables t on t.id = b.table_id
where s.id = ?
`

func (q *Queries) GetTableFromSheet(ctx context.Context, id uuid.UUID) (Table, error) {
	row := q.db.QueryRowContext(ctx, getTableFromSheet, id)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.GameUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
