// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_table.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getTable = `-- name: GetTable :one
select id, game_url, created_at, updated_at, name from tables
where id = ?
`

func (q *Queries) GetTable(ctx context.Context, id uuid.UUID) (Table, error) {
	row := q.db.QueryRowContext(ctx, getTable, id)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.GameUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
