// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_oldest_branch_from_table.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getOldestBranchFromTable = `-- name: GetOldestBranchFromTable :one
select id, name, table_id, created_at, updated_at, is_protected from branches
where table_id = ?
order by created_at asc
limit 1
`

func (q *Queries) GetOldestBranchFromTable(ctx context.Context, tableID uuid.UUID) (Branch, error) {
	row := q.db.QueryRowContext(ctx, getOldestBranchFromTable, tableID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TableID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsProtected,
	)
	return i, err
}
