// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_user_tables.sql

package database

import (
	"context"
)

const getUserTables = `-- name: GetUserTables :one
select user_id, table_id, branch_id, sheet_id, permission, created_at, updated_at from user_tables
where user_id = ? and table_id = ?
`

type GetUserTablesParams struct {
	UserID  interface{}
	TableID interface{}
}

func (q *Queries) GetUserTables(ctx context.Context, arg GetUserTablesParams) (UserTable, error) {
	row := q.db.QueryRowContext(ctx, getUserTables, arg.UserID, arg.TableID)
	var i UserTable
	err := row.Scan(
		&i.UserID,
		&i.TableID,
		&i.BranchID,
		&i.SheetID,
		&i.Permission,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
