// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_branch.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getBranch = `-- name: GetBranch :one
select id, name, table_id, created_at, updated_at, is_protected from branches
where id = ?
`

func (q *Queries) GetBranch(ctx context.Context, id uuid.UUID) (Branch, error) {
	row := q.db.QueryRowContext(ctx, getBranch, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TableID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsProtected,
	)
	return i, err
}
