// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_column.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getColumn = `-- name: GetColumn :one
SELECT id, name, type, required, sheet_id, created_at, updated_at
FROM columns
WHERE id = ?
`

func (q *Queries) GetColumn(ctx context.Context, id uuid.UUID) (Column, error) {
	row := q.db.QueryRowContext(ctx, getColumn, id)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Required,
		&i.SheetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
