// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Branch struct {
	ID        uuid.UUID
	Name      string
	TableID   uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Column struct {
	ID        uuid.UUID
	Name      string
	Type      string
	Required  bool
	SheetID   uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ColumnDatum struct {
	ID        uuid.UUID
	Idx       int64
	Value     sql.NullString
	ColumnID  uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Sheet struct {
	ID        uuid.UUID
	Name      string
	RowCount  int64
	BranchID  uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Table struct {
	ID        uuid.UUID
	GameUrl   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	OpenedSheet    uuid.NullUUID
}

type UserTable struct {
	UserID     uuid.UUID
	TableID    uuid.UUID
	Permission string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
