// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rename_table.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const renameTable = `-- name: RenameTable :exec
UPDATE tables 
SET name = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type RenameTableParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) RenameTable(ctx context.Context, arg RenameTableParams) error {
	_, err := q.db.ExecContext(ctx, renameTable, arg.Name, arg.ID)
	return err
}
