// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rename_sheet.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const renameSheet = `-- name: RenameSheet :exec
UPDATE sheets 
SET name = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type RenameSheetParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) RenameSheet(ctx context.Context, arg RenameSheetParams) error {
	_, err := q.db.ExecContext(ctx, renameSheet, arg.Name, arg.ID)
	return err
}
