// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: set_opened_sheet.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const setOpenedSheet = `-- name: SetOpenedSheet :exec
UPDATE users
SET opened_sheet = ?
WHERE id = ?
`

type SetOpenedSheetParams struct {
	OpenedSheet uuid.NullUUID
	ID          uuid.UUID
}

func (q *Queries) SetOpenedSheet(ctx context.Context, arg SetOpenedSheetParams) error {
	_, err := q.db.ExecContext(ctx, setOpenedSheet, arg.OpenedSheet, arg.ID)
	return err
}
