// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_column_data.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateColumnData = `-- name: UpdateColumnData :exec
UPDATE column_data
SET value = ?
WHERE id = ?
`

type UpdateColumnDataParams struct {
	Value sql.NullString
	ID    uuid.UUID
}

func (q *Queries) UpdateColumnData(ctx context.Context, arg UpdateColumnDataParams) error {
	_, err := q.db.ExecContext(ctx, updateColumnData, arg.Value, arg.ID)
	return err
}
