// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_user_opened_sheet.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserOpenedSheet = `-- name: UpdateUserOpenedSheet :one
UPDATE users
set opened_sheet = ?, updated_at = datetime('now')
where id = ?
RETURNING id, created_at, updated_at, email, hashed_password, opened_sheet
`

type UpdateUserOpenedSheetParams struct {
	OpenedSheet uuid.NullUUID
	ID          uuid.UUID
}

func (q *Queries) UpdateUserOpenedSheet(ctx context.Context, arg UpdateUserOpenedSheetParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserOpenedSheet, arg.OpenedSheet, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.OpenedSheet,
	)
	return i, err
}
