// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_branch.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateBranch = `-- name: UpdateBranch :exec
UPDATE branches
SET name = ?,
    is_protected = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateBranchParams struct {
	Name        string
	IsProtected bool
	ID          uuid.UUID
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) error {
	_, err := q.db.ExecContext(ctx, updateBranch, arg.Name, arg.IsProtected, arg.ID)
	return err
}
