// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_sheet_row_count.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateSheetRowCount = `-- name: UpdateSheetRowCount :exec
UPDATE sheets 
SET row_count = MAX(row_count, ?),
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateSheetRowCountParams struct {
	MAX interface{}
	ID  uuid.UUID
}

func (q *Queries) UpdateSheetRowCount(ctx context.Context, arg UpdateSheetRowCountParams) error {
	_, err := q.db.ExecContext(ctx, updateSheetRowCount, arg.MAX, arg.ID)
	return err
}
