// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_sheet_row_count.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateSheetRowCount = `-- name: UpdateSheetRowCount :exec
UPDATE sheets
SET row_count = CASE 
    WHEN row_count < ? THEN ?
    ELSE row_count
    END,
    updated_at = datetime('now')
WHERE id = (
    SELECT c.sheet_id 
    FROM columns c 
    WHERE c.id = ?
)
`

type UpdateSheetRowCountParams struct {
	RowCount   int64
	RowCount_2 int64
	ID         uuid.UUID
}

func (q *Queries) UpdateSheetRowCount(ctx context.Context, arg UpdateSheetRowCountParams) error {
	_, err := q.db.ExecContext(ctx, updateSheetRowCount, arg.RowCount, arg.RowCount_2, arg.ID)
	return err
}
