// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_user_table.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserTable = `-- name: UpdateUserTable :exec
UPDATE user_tables
set permission = ?, updated_at = datetime('now')
where user_id = ? and table_id = ?
RETURNING user_id, table_id, permission, created_at, updated_at
`

type UpdateUserTableParams struct {
	Permission string
	UserID     uuid.UUID
	TableID    uuid.UUID
}

func (q *Queries) UpdateUserTable(ctx context.Context, arg UpdateUserTableParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTable, arg.Permission, arg.UserID, arg.TableID)
	return err
}
