// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_column.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateColumn = `-- name: UpdateColumn :exec
UPDATE columns
SET name = ?,
    type = ?,
    required = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateColumnParams struct {
	Name     string
	Type     string
	Required bool
	ID       uuid.UUID
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) error {
	_, err := q.db.ExecContext(ctx, updateColumn,
		arg.Name,
		arg.Type,
		arg.Required,
		arg.ID,
	)
	return err
}
